name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: |
      github.event.pull_request.merged == true ||
      contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Build the Docker image
      run: |
        docker build -t laxmanrayala/guestbook-go .

    - name: Login to Docker Hub
      run: echo "62087321Rr" | docker login -u "laxmanrayala" --password-stdin

    - name: Push the Docker image
      run: docker push laxmanrayala/guestbook-go
